### ISSUE TITLE
Missing configuration in Symfony ORM documentation

### ISSUE THREAD

**Issue by benr77** [ecotoneframework/ecotone-dev#301]
I lost an hour yesterday trying to configure `ecotone/dbal` in my Symfony project.

Only after trawling through several Medium articles did I see this snippet, which is absolutely needed to complete the configuration of `ecotone/dbal` in Symfony with Doctrine ORM.

```yaml
# Add in services.yaml, so Ecotone can discover database connection:
Enqueue\Dbal\DbalConnectionFactory:
 factory: ['Ecotone\Dbal\DbalConnection','createForManagerRegistry']   
 arguments: [ "@doctrine","default" ]
```

It would be good if this was included on one of these two pages:

https://docs.ecotone.tech/modules/symfony/symfony-database-connection-dbal-module
https://docs.ecotone.tech/modules/symfony/doctrine-orm

Thanks

PS: As a new Ecotone user, I find the documentation pretty good. However, it is quite difficult to keep track of where you read things as information is spread around over Github, Medium article and the main documentation at https://docs.ecotone.tech/. It would be great if it was all centralised.

**Comment by dgafka** [comment]
Hey @benr77,

This way is legacy way of setting up manager registry
```yaml
Enqueue\Dbal\DbalConnectionFactory:
 factory: ['Ecotone\Dbal\DbalConnection','createForManagerRegistry']   
 arguments: [ "@doctrine","default" ]
```

The current way is like it's described in [the link you've mentioned](https://docs.ecotone.tech/modules/symfony/symfony-database-connection-dbal-module#using-manager-registry).

```php
final readonly class EcotoneConfiguration
{
    #[ServiceContext]
    public function dbalConfiguration()
    {
        return SymfonyConnectionReference::defaultManagerRegistry('some_orm_connection');
    }
}
```
And you should be ready to go

**Comment by benr77** [comment]
Previously, to get things working I've had

```php
#[ServiceContext]
public function getDbalConfiguration(): DbalConfiguration
{
    return DbalConfiguration::createWithDefaults()
        ->withDoctrineORMRepositories(true);
}
```

and also in services.yaml

```yaml
Enqueue\Dbal\DbalConnectionFactory:
 factory: ['Ecotone\Dbal\DbalConnection','createForManagerRegistry']   
 arguments: [ "@doctrine","default" ]
```

Now, I've tried doing as you suggest, and now I'm getting the error:

```
There is no repository available for aggregate: App\Entity\MyEntity
```

I must also be missing some configuration to autoconfigure the generic repository for this aggregate. Any pointers?

Thanks
